service: category-spider

provider:
  name: aws
  runtime: python3.7
  memorySize: 512   # MB ram
  timeout: 60       # seconds

# https://medium.com/@glicht/serverless-framework-defining-per-function-iam-roles-c678fa09f46d
functions:
  s3-json-to-dynamodb:
    handler: s3_json_to_dynamodb.handler
    events:
      - s3:
          bucket: ${self:custom.bucket_name}
          event: s3:ObjectCreated:*
          rules:
            - suffix: .json
    iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:Get*
        - s3:List*
      Resource: arn:aws:s3:::${self:custom.bucket_name}/*
    - Effect: Allow
      Action:
        - dynamodb:BatchWriteItem
      Resource: arn:aws:dynamodb:*:*:table/competitor_analysis_*

custom:
  bucket_name: made-${opt:stage, 'dev'}-competitor-analysis

plugins:
  - serverless-iam-roles-per-function

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: competitor_analysis_overall_${opt:stage, 'dev'}
        AttributeDefinitions:
          - AttributeName: country_competitor_category
            AttributeType: S
          - AttributeName: timestamp
            AttributeType: S
        KeySchema:
          - AttributeName: country_competitor_category
            KeyType: HASH
          - AttributeName: timestamp
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 3
          WriteCapacityUnits: 3
