service: competitor-analysis

provider:
  name: aws
  runtime: python3.7
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:Get*
        - s3:List*
      Resource: "arn:aws:s3:::made-competitor-analysis/*"
    - Effect: "Allow"
      Action:
        - dynamodb:BatchWriteItem
      Resource: "arn:aws:dynamodb:*:*:table/*"

functions:
  category-output:
    handler: handler.handler
    events:
      - s3:
          bucket: made-competitor-analysis
          event: s3:ObjectCreated:*
          rules:
            - prefix: category/
            - suffix: .json

#custom:
#  pythonRequirements:
#    dockerizePip: true

#plugins:
#  - serverless-python-requirements
